import { readFileSync, writeFileSync } from "fs";

const LOCALES = ["en","cs","sk","de","es","fr","pt","nl","pl","it"];

const translations = {
  en: {
    v2HeroHeading: "The creator economy\nthat grows with you.",
    v2HeroSub: "AlphaGlow — where creators publish AI-powered sessions and users earn NSVX for showing up.",
    v2CardUsersTitle: "For Users",
    v2CardUsersBody: "Practice earns NSVX. Nova remembers everything.",
    v2CardUsersLink: "How it works for you",
    v2CardCreatorsTitle: "For Creators",
    v2CardCreatorsBody: "Build sessions. Earn while you sleep.",
    v2CardCreatorsLink: "Creator programme",
    v2CardAdvertisersTitle: "For Advertisers",
    v2CardAdvertisersBody: "78% completion rate. Cost-per-verified-attention.",
    v2CardAdvertisersLink: "Advertiser details",
    v2CardInvestorsTitle: "For Investors",
    v2CardInvestorsBody: "Building infrastructure for the AI creator economy.",
    v2CardInvestorsLink: "Investor overview",
    v2BrandPrimary: "Not who wins. Who grows.",
    v2BrandSecondary: "AlphaGlow is the only platform where your practice builds an economy — for creators, for users, for the future.",
  },
  cs: {
    v2HeroHeading: "Ekonomika tvůrců,\nkterá roste s vámi.",
    v2HeroSub: "AlphaGlow — kde tvůrci budují relace s umělou inteligencí a uživatelé získávají NSVX za účast.",
    v2CardUsersTitle: "Pro uživatele",
    v2CardUsersBody: "Praxe přináší NSVX. Nova si pamatuje vše.",
    v2CardUsersLink: "Jak to funguje",
    v2CardCreatorsTitle: "Pro tvůrce",
    v2CardCreatorsBody: "Vytvářejte relace. Vydělávejte ve spánku.",
    v2CardCreatorsLink: "Program pro tvůrce",
    v2CardAdvertisersTitle: "Pro inzerenty",
    v2CardAdvertisersBody: "78% míra dokončení. Cena za ověřenou pozornost.",
    v2CardAdvertisersLink: "Podrobnosti pro inzerenty",
    v2CardInvestorsTitle: "Pro investory",
    v2CardInvestorsBody: "Budujeme infrastrukturu ekonomiky tvůrců s umělou inteligencí.",
    v2CardInvestorsLink: "Přehled pro investory",
    v2BrandPrimary: "Ne kdo vyhraje. Kdo roste.",
    v2BrandSecondary: "AlphaGlow je jediná platforma, kde vaše praxe buduje ekonomiku — pro tvůrce, uživatele i budoucnost.",
  },
  sk: {
    v2HeroHeading: "Ekonomika tvorcov,\nktorá rastie s vami.",
    v2HeroSub: "AlphaGlow — kde tvorcovia vytvárajú relácie s AI a používatelia zarábajú NSVX za účasť.",
    v2CardUsersTitle: "Pre používateľov",
    v2CardUsersBody: "Prax prináša NSVX. Nova si pamätá všetko.",
    v2CardUsersLink: "Ako to funguje",
    v2CardCreatorsTitle: "Pre tvorcov",
    v2CardCreatorsBody: "Vytvárajte relácie. Zarábajte počas spánku.",
    v2CardCreatorsLink: "Program pre tvorcov",
    v2CardAdvertisersTitle: "Pre inzerentov",
    v2CardAdvertisersBody: "78% miera dokončenia. Cena za overenú pozornosť.",
    v2CardAdvertisersLink: "Podrobnosti pre inzerentov",
    v2CardInvestorsTitle: "Pre investorov",
    v2CardInvestorsBody: "Budujeme infraštruktúru ekonomiky tvorcov s AI.",
    v2CardInvestorsLink: "Prehľad pre investorov",
    v2BrandPrimary: "Nie kto vyhráva. Kto rastie.",
    v2BrandSecondary: "AlphaGlow je jediná platforma, kde vaša prax buduje ekonomiku — pre tvorcov, používateľov aj budúcnosť.",
  },
  de: {
    v2HeroHeading: "Die Creator-Wirtschaft,\ndie mit dir wächst.",
    v2HeroSub: "AlphaGlow — wo Creators KI-Sitzungen veröffentlichen und Nutzer NSVX verdienen.",
    v2CardUsersTitle: "Für Nutzer",
    v2CardUsersBody: "Praxis bringt NSVX. Nova erinnert sich an alles.",
    v2CardUsersLink: "So funktioniert es",
    v2CardCreatorsTitle: "Für Creators",
    v2CardCreatorsBody: "Erstelle Sessions. Verdiene im Schlaf.",
    v2CardCreatorsLink: "Creator-Programm",
    v2CardAdvertisersTitle: "Für Werbetreibende",
    v2CardAdvertisersBody: "78% Abschlussrate. Kosten pro verifizierten Kontakt.",
    v2CardAdvertisersLink: "Werbedetails",
    v2CardInvestorsTitle: "Für Investoren",
    v2CardInvestorsBody: "Infrastruktur für die KI-Creator-Wirtschaft aufbauen.",
    v2CardInvestorsLink: "Investoren-Übersicht",
    v2BrandPrimary: "Nicht wer gewinnt. Wer wächst.",
    v2BrandSecondary: "AlphaGlow ist die einzige Plattform, auf der deine Praxis eine Wirtschaft aufbaut — für Creators, Nutzer und die Zukunft.",
  },
  es: {
    v2HeroHeading: "La economía creadora\nque crece contigo.",
    v2HeroSub: "AlphaGlow — donde los creadores publican sesiones con IA y los usuarios ganan NSVX por participar.",
    v2CardUsersTitle: "Para usuarios",
    v2CardUsersBody: "La práctica genera NSVX. Nova recuerda todo.",
    v2CardUsersLink: "Cómo funciona",
    v2CardCreatorsTitle: "Para creadores",
    v2CardCreatorsBody: "Crea sesiones. Gana mientras duermes.",
    v2CardCreatorsLink: "Programa creador",
    v2CardAdvertisersTitle: "Para anunciantes",
    v2CardAdvertisersBody: "78% de tasa de finalización. Coste por atención verificada.",
    v2CardAdvertisersLink: "Detalles para anunciantes",
    v2CardInvestorsTitle: "Para inversores",
    v2CardInvestorsBody: "Construyendo infraestructura para la economía creadora con IA.",
    v2CardInvestorsLink: "Resumen para inversores",
    v2BrandPrimary: "No quién gana. Quién crece.",
    v2BrandSecondary: "AlphaGlow es la única plataforma donde tu práctica construye una economía — para creadores, usuarios y el futuro.",
  },
  fr: {
    v2HeroHeading: "L'économie créative\nqui grandit avec vous.",
    v2HeroSub: "AlphaGlow — où les créateurs publient des sessions IA et les utilisateurs gagnent des NSVX.",
    v2CardUsersTitle: "Pour les utilisateurs",
    v2CardUsersBody: "La pratique génère des NSVX. Nova se souvient de tout.",
    v2CardUsersLink: "Comment ça marche",
    v2CardCreatorsTitle: "Pour les créateurs",
    v2CardCreatorsBody: "Créez des sessions. Gagnez pendant votre sommeil.",
    v2CardCreatorsLink: "Programme créateur",
    v2CardAdvertisersTitle: "Pour les annonceurs",
    v2CardAdvertisersBody: "78% de taux de complétion. Coût par attention vérifiée.",
    v2CardAdvertisersLink: "Détails annonceurs",
    v2CardInvestorsTitle: "Pour les investisseurs",
    v2CardInvestorsBody: "Construire l'infrastructure de l'économie créative IA.",
    v2CardInvestorsLink: "Aperçu investisseurs",
    v2BrandPrimary: "Pas qui gagne. Qui grandit.",
    v2BrandSecondary: "AlphaGlow est la seule plateforme où votre pratique construit une économie — pour les créateurs, les utilisateurs et l'avenir.",
  },
  pt: {
    v2HeroHeading: "A economia criativa\nque cresce com você.",
    v2HeroSub: "AlphaGlow — onde criadores publicam sessões com IA e usuários ganham NSVX por participar.",
    v2CardUsersTitle: "Para usuários",
    v2CardUsersBody: "A prática gera NSVX. Nova lembra de tudo.",
    v2CardUsersLink: "Como funciona",
    v2CardCreatorsTitle: "Para criadores",
    v2CardCreatorsBody: "Crie sessões. Ganhe enquanto dorme.",
    v2CardCreatorsLink: "Programa de criador",
    v2CardAdvertisersTitle: "Para anunciantes",
    v2CardAdvertisersBody: "78% de taxa de conclusão. Custo por atenção verificada.",
    v2CardAdvertisersLink: "Detalhes para anunciantes",
    v2CardInvestorsTitle: "Para investidores",
    v2CardInvestorsBody: "Construindo infraestrutura para a economia criativa com IA.",
    v2CardInvestorsLink: "Visão geral para investidores",
    v2BrandPrimary: "Não quem vence. Quem cresce.",
    v2BrandSecondary: "AlphaGlow é a única plataforma onde sua prática constrói uma economia — para criadores, usuários e o futuro.",
  },
  nl: {
    v2HeroHeading: "De creator-economie\ndie met je meegroeit.",
    v2HeroSub: "AlphaGlow — waar creators AI-sessies publiceren en gebruikers NSVX verdienen.",
    v2CardUsersTitle: "Voor gebruikers",
    v2CardUsersBody: "Oefening levert NSVX op. Nova onthoudt alles.",
    v2CardUsersLink: "Hoe het werkt",
    v2CardCreatorsTitle: "Voor creators",
    v2CardCreatorsBody: "Maak sessies. Verdien terwijl je slaapt.",
    v2CardCreatorsLink: "Creator-programma",
    v2CardAdvertisersTitle: "Voor adverteerders",
    v2CardAdvertisersBody: "78% voltooiingspercentage. Kosten per geverifieerde aandacht.",
    v2CardAdvertisersLink: "Details voor adverteerders",
    v2CardInvestorsTitle: "Voor investeerders",
    v2CardInvestorsBody: "Infrastructuur bouwen voor de AI creator-economie.",
    v2CardInvestorsLink: "Overzicht investeerders",
    v2BrandPrimary: "Niet wie wint. Wie groeit.",
    v2BrandSecondary: "AlphaGlow is het enige platform waar je praktijk een economie opbouwt — voor creators, gebruikers en de toekomst.",
  },
  pl: {
    v2HeroHeading: "Gospodarka twórców,\nktóra rośnie razem z tobą.",
    v2HeroSub: "AlphaGlow — gdzie twórcy publikują sesje AI, a użytkownicy zarabiają NSVX za uczestnictwo.",
    v2CardUsersTitle: "Dla użytkowników",
    v2CardUsersBody: "Praktyka przynosi NSVX. Nova pamięta wszystko.",
    v2CardUsersLink: "Jak to działa",
    v2CardCreatorsTitle: "Dla twórców",
    v2CardCreatorsBody: "Twórz sesje. Zarabiaj podczas snu.",
    v2CardCreatorsLink: "Program twórcy",
    v2CardAdvertisersTitle: "Dla reklamodawców",
    v2CardAdvertisersBody: "78% wskaźnik ukończenia. Koszt za potwierdzoną uwagę.",
    v2CardAdvertisersLink: "Szczegóły dla reklamodawców",
    v2CardInvestorsTitle: "Dla inwestorów",
    v2CardInvestorsBody: "Budujemy infrastrukturę gospodarki twórców opartej na AI.",
    v2CardInvestorsLink: "Przegląd dla inwestorów",
    v2BrandPrimary: "Nie kto wygrywa. Kto rośnie.",
    v2BrandSecondary: "AlphaGlow to jedyna platforma, gdzie twoja praktyka buduje gospodarkę — dla twórców, użytkowników i przyszłości.",
  },
  it: {
    v2HeroHeading: "L'economia dei creator\nche cresce con te.",
    v2HeroSub: "AlphaGlow — dove i creator pubblicano sessioni AI e gli utenti guadagnano NSVX partecipando.",
    v2CardUsersTitle: "Per gli utenti",
    v2CardUsersBody: "La pratica genera NSVX. Nova ricorda tutto.",
    v2CardUsersLink: "Come funziona",
    v2CardCreatorsTitle: "Per i creator",
    v2CardCreatorsBody: "Crea sessioni. Guadagna mentre dormi.",
    v2CardCreatorsLink: "Programma creator",
    v2CardAdvertisersTitle: "Per gli inserzionisti",
    v2CardAdvertisersBody: "78% di tasso di completamento. Costo per attenzione verificata.",
    v2CardAdvertisersLink: "Dettagli per inserzionisti",
    v2CardInvestorsTitle: "Per gli investitori",
    v2CardInvestorsBody: "Costruiamo l'infrastruttura per l'economia AI dei creator.",
    v2CardInvestorsLink: "Panoramica investitori",
    v2BrandPrimary: "Non chi vince. Chi cresce.",
    v2BrandSecondary: "AlphaGlow è l'unica piattaforma dove la tua pratica costruisce un'economia — per creator, utenti e il futuro.",
  },
};

for (const locale of LOCALES) {
  const path = `C:/ai-tools/agai-web/locales/${locale}.json`;
  const raw = readFileSync(path, "utf8");
  const bom = raw.charCodeAt(0) === 0xfeff;
  const d = JSON.parse(bom ? raw.slice(1) : raw);
  if (!d.home) d.home = {};
  Object.assign(d.home, translations[locale]);
  writeFileSync(path, (bom ? "﻿" : "") + JSON.stringify(d, null, 2), "utf8");
  console.log(`${locale}.json updated`);
}
